package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * Md52keywords generated by hbm2java
 */
public class Md52keywords implements java.io.Serializable {

	private String md5;
	private String geneSymbol;
	private String geneSp;
	private String description;

	public Md52keywords() {
	}

	public Md52keywords(String md5) {
		this.md5 = md5;
	}

	public Md52keywords(String md5, String geneSymbol, String geneSp,
			String description) {
		this.md5 = md5;
		this.geneSymbol = geneSymbol;
		this.geneSp = geneSp;
		this.description = description;
	}

	public String getMd5() {
		return this.md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	public String getGeneSymbol() {
		return this.geneSymbol;
	}

	public void setGeneSymbol(String geneSymbol) {
		this.geneSymbol = geneSymbol;
	}

	public String getGeneSp() {
		return this.geneSp;
	}

	public void setGeneSp(String geneSp) {
		this.geneSp = geneSp;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
