package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * Omim2diseaseId generated by hbm2java
 */
public class Omim2diseaseId implements java.io.Serializable {

	private int omimId;
	private String varId;

	public Omim2diseaseId() {
	}

	public Omim2diseaseId(int omimId, String varId) {
		this.omimId = omimId;
		this.varId = varId;
	}

	public int getOmimId() {
		return this.omimId;
	}

	public void setOmimId(int omimId) {
		this.omimId = omimId;
	}

	public String getVarId() {
		return this.varId;
	}

	public void setVarId(String varId) {
		this.varId = varId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Omim2diseaseId))
			return false;
		Omim2diseaseId castOther = (Omim2diseaseId) other;

		return (this.getOmimId() == castOther.getOmimId())
				&& ((this.getVarId() == castOther.getVarId()) || (this
						.getVarId() != null && castOther.getVarId() != null && this
						.getVarId().equals(castOther.getVarId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOmimId();
		result = 37 * result
				+ (getVarId() == null ? 0 : this.getVarId().hashCode());
		return result;
	}

}
