package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SeqsContainingSnps generated by hbm2java
 */
public class SeqsContainingSnps implements java.io.Serializable {

	private String md5;
	private String seq;
	private String inDbSnp;
	private String inSp;
	private String inPmd;
	private String in1kg;

	public SeqsContainingSnps() {
	}

	public SeqsContainingSnps(String md5, String seq, String inDbSnp,
			String inSp, String inPmd) {
		this.md5 = md5;
		this.seq = seq;
		this.inDbSnp = inDbSnp;
		this.inSp = inSp;
		this.inPmd = inPmd;
	}

	public SeqsContainingSnps(String md5, String seq, String inDbSnp,
			String inSp, String inPmd, String in1kg) {
		this.md5 = md5;
		this.seq = seq;
		this.inDbSnp = inDbSnp;
		this.inSp = inSp;
		this.inPmd = inPmd;
		this.in1kg = in1kg;
	}

	public String getMd5() {
		return this.md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public String getInDbSnp() {
		return this.inDbSnp;
	}

	public void setInDbSnp(String inDbSnp) {
		this.inDbSnp = inDbSnp;
	}

	public String getInSp() {
		return this.inSp;
	}

	public void setInSp(String inSp) {
		this.inSp = inSp;
	}

	public String getInPmd() {
		return this.inPmd;
	}

	public void setInPmd(String inPmd) {
		this.inPmd = inPmd;
	}

	public String getIn1kg() {
		return this.in1kg;
	}

	public void setIn1kg(String in1kg) {
		this.in1kg = in1kg;
	}

}
