package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SeqsRefSeq generated by hbm2java
 */
public class SeqsRefSeq implements java.io.Serializable {

	private SeqsRefSeqId id;
	private String md5;
	private String seq;
	private int gi;
	private String comment;
	private int taxid;
	private String inDbSnp;
	private String in1kg;

	public SeqsRefSeq() {
	}

	public SeqsRefSeq(SeqsRefSeqId id, String md5, String seq, int gi,
			String comment, int taxid, String inDbSnp, String in1kg) {
		this.id = id;
		this.md5 = md5;
		this.seq = seq;
		this.gi = gi;
		this.comment = comment;
		this.taxid = taxid;
		this.inDbSnp = inDbSnp;
		this.in1kg = in1kg;
	}

	public SeqsRefSeqId getId() {
		return this.id;
	}

	public void setId(SeqsRefSeqId id) {
		this.id = id;
	}

	public String getMd5() {
		return this.md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public int getGi() {
		return this.gi;
	}

	public void setGi(int gi) {
		this.gi = gi;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public int getTaxid() {
		return this.taxid;
	}

	public void setTaxid(int taxid) {
		this.taxid = taxid;
	}

	public String getInDbSnp() {
		return this.inDbSnp;
	}

	public void setInDbSnp(String inDbSnp) {
		this.inDbSnp = inDbSnp;
	}

	public String getIn1kg() {
		return this.in1kg;
	}

	public void setIn1kg(String in1kg) {
		this.in1kg = in1kg;
	}

}
