package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SeqsEqualitiesId generated by hbm2java
 */
public class SeqsEqualitiesId implements java.io.Serializable {

	private String md51;
	private String md52;

	public SeqsEqualitiesId() {
	}

	public SeqsEqualitiesId(String md51, String md52) {
		this.md51 = md51;
		this.md52 = md52;
	}

	public String getMd51() {
		return this.md51;
	}

	public void setMd51(String md51) {
		this.md51 = md51;
	}

	public String getMd52() {
		return this.md52;
	}

	public void setMd52(String md52) {
		this.md52 = md52;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeqsEqualitiesId))
			return false;
		SeqsEqualitiesId castOther = (SeqsEqualitiesId) other;

		return ((this.getMd51() == castOther.getMd51()) || (this.getMd51() != null
				&& castOther.getMd51() != null && this.getMd51().equals(
				castOther.getMd51())))
				&& ((this.getMd52() == castOther.getMd52()) || (this.getMd52() != null
						&& castOther.getMd52() != null && this.getMd52()
						.equals(castOther.getMd52())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMd51() == null ? 0 : this.getMd51().hashCode());
		result = 37 * result
				+ (getMd52() == null ? 0 : this.getMd52().hashCode());
		return result;
	}

}
