package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SeqsSp generated by hbm2java
 */
public class SeqsSp implements java.io.Serializable {

	private String ac;
	private String md5;
	private String seq;
	private String id;
	private String gene;
	private int taxid;
	private String description;

	public SeqsSp() {
	}

	public SeqsSp(String ac, String md5, String seq, int taxid) {
		this.ac = ac;
		this.md5 = md5;
		this.seq = seq;
		this.taxid = taxid;
	}

	public SeqsSp(String ac, String md5, String seq, String id, String gene,
			int taxid, String description) {
		this.ac = ac;
		this.md5 = md5;
		this.seq = seq;
		this.id = id;
		this.gene = gene;
		this.taxid = taxid;
		this.description = description;
	}

	public String getAc() {
		return this.ac;
	}

	public void setAc(String ac) {
		this.ac = ac;
	}

	public String getMd5() {
		return this.md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGene() {
		return this.gene;
	}

	public void setGene(String gene) {
		this.gene = gene;
	}

	public int getTaxid() {
		return this.taxid;
	}

	public void setTaxid(int taxid) {
		this.taxid = taxid;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
