package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SeqsEqualities generated by hbm2java
 */
public class SeqsEqualities implements java.io.Serializable {

	private SeqsEqualitiesId id;
	private String byMissingM;
	private String byOneMismatch;
	private Short posMismatch;

	public SeqsEqualities() {
	}

	public SeqsEqualities(SeqsEqualitiesId id, String byMissingM,
			String byOneMismatch) {
		this.id = id;
		this.byMissingM = byMissingM;
		this.byOneMismatch = byOneMismatch;
	}

	public SeqsEqualities(SeqsEqualitiesId id, String byMissingM,
			String byOneMismatch, Short posMismatch) {
		this.id = id;
		this.byMissingM = byMissingM;
		this.byOneMismatch = byOneMismatch;
		this.posMismatch = posMismatch;
	}

	public SeqsEqualitiesId getId() {
		return this.id;
	}

	public void setId(SeqsEqualitiesId id) {
		this.id = id;
	}

	public String getByMissingM() {
		return this.byMissingM;
	}

	public void setByMissingM(String byMissingM) {
		this.byMissingM = byMissingM;
	}

	public String getByOneMismatch() {
		return this.byOneMismatch;
	}

	public void setByOneMismatch(String byOneMismatch) {
		this.byOneMismatch = byOneMismatch;
	}

	public Short getPosMismatch() {
		return this.posMismatch;
	}

	public void setPosMismatch(Short posMismatch) {
		this.posMismatch = posMismatch;
	}

}
