package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SeqsRefSeqId generated by hbm2java
 */
public class SeqsRefSeqId implements java.io.Serializable {

	private String id;
	private byte ver;

	public SeqsRefSeqId() {
	}

	public SeqsRefSeqId(String id, byte ver) {
		this.id = id;
		this.ver = ver;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public byte getVer() {
		return this.ver;
	}

	public void setVer(byte ver) {
		this.ver = ver;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeqsRefSeqId))
			return false;
		SeqsRefSeqId castOther = (SeqsRefSeqId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& (this.getVer() == castOther.getVer());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + this.getVer();
		return result;
	}

}
