package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SnpsDbSnp generated by hbm2java
 */
public class SnpsDbSnp implements java.io.Serializable {

	private SnpsDbSnpId id;
	private Integer mutId;
	private String verified;
	private String md5;
	private Byte contigVer;
	private int asnFrom;
	private int asnTo;
	private Integer locusId;
	private String locusSymbol;
	private String mrnaAcc;
	private Integer proteinVer;
	private Integer readingFrame;
	private String mt;
	private int ctgId;
	private Integer mrnaPos;
	private Integer mrnaStart;
	private Integer mrnaStop;
	private String codon;
	private String protRes;
	private Integer contigGi;
	private Integer mrnaGi;
	private Byte mrnaOrien;
	private Integer cpMrnaVer;
	private Integer cpMrnaGi;
	private String verComp;

	public SnpsDbSnp() {
	}

	public SnpsDbSnp(SnpsDbSnpId id, String verified, String md5, int asnFrom,
			int asnTo, String locusSymbol, String mrnaAcc, int ctgId) {
		this.id = id;
		this.verified = verified;
		this.md5 = md5;
		this.asnFrom = asnFrom;
		this.asnTo = asnTo;
		this.locusSymbol = locusSymbol;
		this.mrnaAcc = mrnaAcc;
		this.ctgId = ctgId;
	}

	public SnpsDbSnp(SnpsDbSnpId id, Integer mutId, String verified,
			String md5, Byte contigVer, int asnFrom, int asnTo,
			Integer locusId, String locusSymbol, String mrnaAcc,
			Integer proteinVer, Integer readingFrame, String mt, int ctgId,
			Integer mrnaPos, Integer mrnaStart, Integer mrnaStop, String codon,
			String protRes, Integer contigGi, Integer mrnaGi, Byte mrnaOrien,
			Integer cpMrnaVer, Integer cpMrnaGi, String verComp) {
		this.id = id;
		this.mutId = mutId;
		this.verified = verified;
		this.md5 = md5;
		this.contigVer = contigVer;
		this.asnFrom = asnFrom;
		this.asnTo = asnTo;
		this.locusId = locusId;
		this.locusSymbol = locusSymbol;
		this.mrnaAcc = mrnaAcc;
		this.proteinVer = proteinVer;
		this.readingFrame = readingFrame;
		this.mt = mt;
		this.ctgId = ctgId;
		this.mrnaPos = mrnaPos;
		this.mrnaStart = mrnaStart;
		this.mrnaStop = mrnaStop;
		this.codon = codon;
		this.protRes = protRes;
		this.contigGi = contigGi;
		this.mrnaGi = mrnaGi;
		this.mrnaOrien = mrnaOrien;
		this.cpMrnaVer = cpMrnaVer;
		this.cpMrnaGi = cpMrnaGi;
		this.verComp = verComp;
	}

	public SnpsDbSnpId getId() {
		return this.id;
	}

	public void setId(SnpsDbSnpId id) {
		this.id = id;
	}

	public Integer getMutId() {
		return this.mutId;
	}

	public void setMutId(Integer mutId) {
		this.mutId = mutId;
	}

	public String getVerified() {
		return this.verified;
	}

	public void setVerified(String verified) {
		this.verified = verified;
	}

	public String getMd5() {
		return this.md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	public Byte getContigVer() {
		return this.contigVer;
	}

	public void setContigVer(Byte contigVer) {
		this.contigVer = contigVer;
	}

	public int getAsnFrom() {
		return this.asnFrom;
	}

	public void setAsnFrom(int asnFrom) {
		this.asnFrom = asnFrom;
	}

	public int getAsnTo() {
		return this.asnTo;
	}

	public void setAsnTo(int asnTo) {
		this.asnTo = asnTo;
	}

	public Integer getLocusId() {
		return this.locusId;
	}

	public void setLocusId(Integer locusId) {
		this.locusId = locusId;
	}

	public String getLocusSymbol() {
		return this.locusSymbol;
	}

	public void setLocusSymbol(String locusSymbol) {
		this.locusSymbol = locusSymbol;
	}

	public String getMrnaAcc() {
		return this.mrnaAcc;
	}

	public void setMrnaAcc(String mrnaAcc) {
		this.mrnaAcc = mrnaAcc;
	}

	public Integer getProteinVer() {
		return this.proteinVer;
	}

	public void setProteinVer(Integer proteinVer) {
		this.proteinVer = proteinVer;
	}

	public Integer getReadingFrame() {
		return this.readingFrame;
	}

	public void setReadingFrame(Integer readingFrame) {
		this.readingFrame = readingFrame;
	}

	public String getMt() {
		return this.mt;
	}

	public void setMt(String mt) {
		this.mt = mt;
	}

	public int getCtgId() {
		return this.ctgId;
	}

	public void setCtgId(int ctgId) {
		this.ctgId = ctgId;
	}

	public Integer getMrnaPos() {
		return this.mrnaPos;
	}

	public void setMrnaPos(Integer mrnaPos) {
		this.mrnaPos = mrnaPos;
	}

	public Integer getMrnaStart() {
		return this.mrnaStart;
	}

	public void setMrnaStart(Integer mrnaStart) {
		this.mrnaStart = mrnaStart;
	}

	public Integer getMrnaStop() {
		return this.mrnaStop;
	}

	public void setMrnaStop(Integer mrnaStop) {
		this.mrnaStop = mrnaStop;
	}

	public String getCodon() {
		return this.codon;
	}

	public void setCodon(String codon) {
		this.codon = codon;
	}

	public String getProtRes() {
		return this.protRes;
	}

	public void setProtRes(String protRes) {
		this.protRes = protRes;
	}

	public Integer getContigGi() {
		return this.contigGi;
	}

	public void setContigGi(Integer contigGi) {
		this.contigGi = contigGi;
	}

	public Integer getMrnaGi() {
		return this.mrnaGi;
	}

	public void setMrnaGi(Integer mrnaGi) {
		this.mrnaGi = mrnaGi;
	}

	public Byte getMrnaOrien() {
		return this.mrnaOrien;
	}

	public void setMrnaOrien(Byte mrnaOrien) {
		this.mrnaOrien = mrnaOrien;
	}

	public Integer getCpMrnaVer() {
		return this.cpMrnaVer;
	}

	public void setCpMrnaVer(Integer cpMrnaVer) {
		this.cpMrnaVer = cpMrnaVer;
	}

	public Integer getCpMrnaGi() {
		return this.cpMrnaGi;
	}

	public void setCpMrnaGi(Integer cpMrnaGi) {
		this.cpMrnaGi = cpMrnaGi;
	}

	public String getVerComp() {
		return this.verComp;
	}

	public void setVerComp(String verComp) {
		this.verComp = verComp;
	}

}
