package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SnpsSp generated by hbm2java
 */
public class SnpsSp implements java.io.Serializable {

	private SnpsSpId id;
	private int mutId;
	private int taxid;
	private String siteFeatures;
	private String functionalEffect;
	private String varId;
	private String disease;

	public SnpsSp() {
	}

	public SnpsSp(SnpsSpId id, int mutId, int taxid) {
		this.id = id;
		this.mutId = mutId;
		this.taxid = taxid;
	}

	public SnpsSp(SnpsSpId id, int mutId, int taxid, String siteFeatures,
			String functionalEffect, String varId, String disease) {
		this.id = id;
		this.mutId = mutId;
		this.taxid = taxid;
		this.siteFeatures = siteFeatures;
		this.functionalEffect = functionalEffect;
		this.varId = varId;
		this.disease = disease;
	}

	public SnpsSpId getId() {
		return this.id;
	}

	public void setId(SnpsSpId id) {
		this.id = id;
	}

	public int getMutId() {
		return this.mutId;
	}

	public void setMutId(int mutId) {
		this.mutId = mutId;
	}

	public int getTaxid() {
		return this.taxid;
	}

	public void setTaxid(int taxid) {
		this.taxid = taxid;
	}

	public String getSiteFeatures() {
		return this.siteFeatures;
	}

	public void setSiteFeatures(String siteFeatures) {
		this.siteFeatures = siteFeatures;
	}

	public String getFunctionalEffect() {
		return this.functionalEffect;
	}

	public void setFunctionalEffect(String functionalEffect) {
		this.functionalEffect = functionalEffect;
	}

	public String getVarId() {
		return this.varId;
	}

	public void setVarId(String varId) {
		this.varId = varId;
	}

	public String getDisease() {
		return this.disease;
	}

	public void setDisease(String disease) {
		this.disease = disease;
	}

}
