package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SnpsDbSnpId generated by hbm2java
 */
public class SnpsDbSnpId implements java.io.Serializable {

	private int taxid;
	private short build;
	private String assembly;
	private String proteinAcc;
	private int pos;
	private int snpId;
	private String allele;
	private int fxnClass;
	private int mrnaVer;
	private String contigAcc;

	public SnpsDbSnpId() {
	}

	public SnpsDbSnpId(int taxid, short build, String assembly,
			String proteinAcc, int pos, int snpId, String allele, int fxnClass,
			int mrnaVer, String contigAcc) {
		this.taxid = taxid;
		this.build = build;
		this.assembly = assembly;
		this.proteinAcc = proteinAcc;
		this.pos = pos;
		this.snpId = snpId;
		this.allele = allele;
		this.fxnClass = fxnClass;
		this.mrnaVer = mrnaVer;
		this.contigAcc = contigAcc;
	}

	public int getTaxid() {
		return this.taxid;
	}

	public void setTaxid(int taxid) {
		this.taxid = taxid;
	}

	public short getBuild() {
		return this.build;
	}

	public void setBuild(short build) {
		this.build = build;
	}

	public String getAssembly() {
		return this.assembly;
	}

	public void setAssembly(String assembly) {
		this.assembly = assembly;
	}

	public String getProteinAcc() {
		return this.proteinAcc;
	}

	public void setProteinAcc(String proteinAcc) {
		this.proteinAcc = proteinAcc;
	}

	public int getPos() {
		return this.pos;
	}

	public void setPos(int pos) {
		this.pos = pos;
	}

	public int getSnpId() {
		return this.snpId;
	}

	public void setSnpId(int snpId) {
		this.snpId = snpId;
	}

	public String getAllele() {
		return this.allele;
	}

	public void setAllele(String allele) {
		this.allele = allele;
	}

	public int getFxnClass() {
		return this.fxnClass;
	}

	public void setFxnClass(int fxnClass) {
		this.fxnClass = fxnClass;
	}

	public int getMrnaVer() {
		return this.mrnaVer;
	}

	public void setMrnaVer(int mrnaVer) {
		this.mrnaVer = mrnaVer;
	}

	public String getContigAcc() {
		return this.contigAcc;
	}

	public void setContigAcc(String contigAcc) {
		this.contigAcc = contigAcc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SnpsDbSnpId))
			return false;
		SnpsDbSnpId castOther = (SnpsDbSnpId) other;

		return (this.getTaxid() == castOther.getTaxid())
				&& (this.getBuild() == castOther.getBuild())
				&& ((this.getAssembly() == castOther.getAssembly()) || (this
						.getAssembly() != null
						&& castOther.getAssembly() != null && this
						.getAssembly().equals(castOther.getAssembly())))
				&& ((this.getProteinAcc() == castOther.getProteinAcc()) || (this
						.getProteinAcc() != null
						&& castOther.getProteinAcc() != null && this
						.getProteinAcc().equals(castOther.getProteinAcc())))
				&& (this.getPos() == castOther.getPos())
				&& (this.getSnpId() == castOther.getSnpId())
				&& ((this.getAllele() == castOther.getAllele()) || (this
						.getAllele() != null && castOther.getAllele() != null && this
						.getAllele().equals(castOther.getAllele())))
				&& (this.getFxnClass() == castOther.getFxnClass())
				&& (this.getMrnaVer() == castOther.getMrnaVer())
				&& ((this.getContigAcc() == castOther.getContigAcc()) || (this
						.getContigAcc() != null
						&& castOther.getContigAcc() != null && this
						.getContigAcc().equals(castOther.getContigAcc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTaxid();
		result = 37 * result + this.getBuild();
		result = 37 * result
				+ (getAssembly() == null ? 0 : this.getAssembly().hashCode());
		result = 37
				* result
				+ (getProteinAcc() == null ? 0 : this.getProteinAcc()
						.hashCode());
		result = 37 * result + this.getPos();
		result = 37 * result + this.getSnpId();
		result = 37 * result
				+ (getAllele() == null ? 0 : this.getAllele().hashCode());
		result = 37 * result + this.getFxnClass();
		result = 37 * result + this.getMrnaVer();
		result = 37 * result
				+ (getContigAcc() == null ? 0 : this.getContigAcc().hashCode());
		return result;
	}

}
