package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SpAcMap generated by hbm2java
 */
public class SpAcMap implements java.io.Serializable {

	private SpAcMapId id;

	public SpAcMap() {
	}

	public SpAcMap(SpAcMapId id) {
		this.id = id;
	}

	public SpAcMapId getId() {
		return this.id;
	}

	public void setId(SpAcMapId id) {
		this.id = id;
	}

}
