package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SpAcMapId generated by hbm2java
 */
public class SpAcMapId implements java.io.Serializable {

	private String first;
	private String additional;

	public SpAcMapId() {
	}

	public SpAcMapId(String first, String additional) {
		this.first = first;
		this.additional = additional;
	}

	public String getFirst() {
		return this.first;
	}

	public void setFirst(String first) {
		this.first = first;
	}

	public String getAdditional() {
		return this.additional;
	}

	public void setAdditional(String additional) {
		this.additional = additional;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpAcMapId))
			return false;
		SpAcMapId castOther = (SpAcMapId) other;

		return ((this.getFirst() == castOther.getFirst()) || (this.getFirst() != null
				&& castOther.getFirst() != null && this.getFirst().equals(
				castOther.getFirst())))
				&& ((this.getAdditional() == castOther.getAdditional()) || (this
						.getAdditional() != null
						&& castOther.getAdditional() != null && this
						.getAdditional().equals(castOther.getAdditional())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFirst() == null ? 0 : this.getFirst().hashCode());
		result = 37
				* result
				+ (getAdditional() == null ? 0 : this.getAdditional()
						.hashCode());
		return result;
	}

}
