package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * DbSnp2omimVerified generated by hbm2java
 */
public class DbSnp2omimVerified implements java.io.Serializable {

	private DbSnp2omimVerifiedId id;

	public DbSnp2omimVerified() {
	}

	public DbSnp2omimVerified(DbSnp2omimVerifiedId id) {
		this.id = id;
	}

	public DbSnp2omimVerifiedId getId() {
		return this.id;
	}

	public void setId(DbSnp2omimVerifiedId id) {
		this.id = id;
	}

}
