package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * DbSnp2omimVerifiedId generated by hbm2java
 */
public class DbSnp2omimVerifiedId implements java.io.Serializable {

	private int mutId;
	private int omimId;
	private String varId;

	public DbSnp2omimVerifiedId() {
	}

	public DbSnp2omimVerifiedId(int mutId, int omimId, String varId) {
		this.mutId = mutId;
		this.omimId = omimId;
		this.varId = varId;
	}

	public int getMutId() {
		return this.mutId;
	}

	public void setMutId(int mutId) {
		this.mutId = mutId;
	}

	public int getOmimId() {
		return this.omimId;
	}

	public void setOmimId(int omimId) {
		this.omimId = omimId;
	}

	public String getVarId() {
		return this.varId;
	}

	public void setVarId(String varId) {
		this.varId = varId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbSnp2omimVerifiedId))
			return false;
		DbSnp2omimVerifiedId castOther = (DbSnp2omimVerifiedId) other;

		return (this.getMutId() == castOther.getMutId())
				&& (this.getOmimId() == castOther.getOmimId())
				&& ((this.getVarId() == castOther.getVarId()) || (this
						.getVarId() != null && castOther.getVarId() != null && this
						.getVarId().equals(castOther.getVarId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMutId();
		result = 37 * result + this.getOmimId();
		result = 37 * result
				+ (getVarId() == null ? 0 : this.getVarId().hashCode());
		return result;
	}

}
