package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * DbSnpSnp generated by hbm2java
 */
public class DbSnpSnp implements java.io.Serializable {

	private int snpId;
	private Float avgHeterozygosity;
	private Float hetSe;
	private String createTime;
	private String lastUpdatedTime;
	private Byte cpGCode;
	private Integer taxid;
	private Byte validationStatus;
	private Integer exemplarSubsnpId;
	private Integer univarId;
	private Byte cntSubsnp;
	private Byte mapProperty;

	public DbSnpSnp() {
	}

	public DbSnpSnp(int snpId) {
		this.snpId = snpId;
	}

	public DbSnpSnp(int snpId, Float avgHeterozygosity, Float hetSe,
			String createTime, String lastUpdatedTime, Byte cpGCode,
			Integer taxid, Byte validationStatus, Integer exemplarSubsnpId,
			Integer univarId, Byte cntSubsnp, Byte mapProperty) {
		this.snpId = snpId;
		this.avgHeterozygosity = avgHeterozygosity;
		this.hetSe = hetSe;
		this.createTime = createTime;
		this.lastUpdatedTime = lastUpdatedTime;
		this.cpGCode = cpGCode;
		this.taxid = taxid;
		this.validationStatus = validationStatus;
		this.exemplarSubsnpId = exemplarSubsnpId;
		this.univarId = univarId;
		this.cntSubsnp = cntSubsnp;
		this.mapProperty = mapProperty;
	}

	public int getSnpId() {
		return this.snpId;
	}

	public void setSnpId(int snpId) {
		this.snpId = snpId;
	}

	public Float getAvgHeterozygosity() {
		return this.avgHeterozygosity;
	}

	public void setAvgHeterozygosity(Float avgHeterozygosity) {
		this.avgHeterozygosity = avgHeterozygosity;
	}

	public Float getHetSe() {
		return this.hetSe;
	}

	public void setHetSe(Float hetSe) {
		this.hetSe = hetSe;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getLastUpdatedTime() {
		return this.lastUpdatedTime;
	}

	public void setLastUpdatedTime(String lastUpdatedTime) {
		this.lastUpdatedTime = lastUpdatedTime;
	}

	public Byte getCpGCode() {
		return this.cpGCode;
	}

	public void setCpGCode(Byte cpGCode) {
		this.cpGCode = cpGCode;
	}

	public Integer getTaxid() {
		return this.taxid;
	}

	public void setTaxid(Integer taxid) {
		this.taxid = taxid;
	}

	public Byte getValidationStatus() {
		return this.validationStatus;
	}

	public void setValidationStatus(Byte validationStatus) {
		this.validationStatus = validationStatus;
	}

	public Integer getExemplarSubsnpId() {
		return this.exemplarSubsnpId;
	}

	public void setExemplarSubsnpId(Integer exemplarSubsnpId) {
		this.exemplarSubsnpId = exemplarSubsnpId;
	}

	public Integer getUnivarId() {
		return this.univarId;
	}

	public void setUnivarId(Integer univarId) {
		this.univarId = univarId;
	}

	public Byte getCntSubsnp() {
		return this.cntSubsnp;
	}

	public void setCntSubsnp(Byte cntSubsnp) {
		this.cntSubsnp = cntSubsnp;
	}

	public Byte getMapProperty() {
		return this.mapProperty;
	}

	public void setMapProperty(Byte mapProperty) {
		this.mapProperty = mapProperty;
	}

}
