package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * Geno2func generated by hbm2java
 */
public class Geno2func implements java.io.Serializable {

	private Geno2funcId id;
	private int mutId;
	private char wt;
	private String inDbSnp;
	private String inSp;
	private String inPmd;
	private String in1kg;
	private String snapStatus;
	private String snapBin;
	private Byte snapScore;
	private Boolean snapRi;
	private Byte snapAcc;
	private String siftBin;
	private Float siftScore;
	private Byte percWt;
	private Byte percMt;
	private Byte pssmWt;
	private Byte pssmMt;
	private Float psicWt;
	private Float psicMt;
	private String pph2;

	public Geno2func() {
	}

	public Geno2func(Geno2funcId id, int mutId, char wt, String snapStatus) {
		this.id = id;
		this.mutId = mutId;
		this.wt = wt;
		this.snapStatus = snapStatus;
	}

	public Geno2func(Geno2funcId id, int mutId, char wt, String inDbSnp,
			String inSp, String inPmd, String in1kg, String snapStatus,
			String snapBin, Byte snapScore, Boolean snapRi, Byte snapAcc,
			String siftBin, Float siftScore, Byte percWt, Byte percMt,
			Byte pssmWt, Byte pssmMt, Float psicWt, Float psicMt, String pph2) {
		this.id = id;
		this.mutId = mutId;
		this.wt = wt;
		this.inDbSnp = inDbSnp;
		this.inSp = inSp;
		this.inPmd = inPmd;
		this.in1kg = in1kg;
		this.snapStatus = snapStatus;
		this.snapBin = snapBin;
		this.snapScore = snapScore;
		this.snapRi = snapRi;
		this.snapAcc = snapAcc;
		this.siftBin = siftBin;
		this.siftScore = siftScore;
		this.percWt = percWt;
		this.percMt = percMt;
		this.pssmWt = pssmWt;
		this.pssmMt = pssmMt;
		this.psicWt = psicWt;
		this.psicMt = psicMt;
		this.pph2 = pph2;
	}

	public Geno2funcId getId() {
		return this.id;
	}

	public void setId(Geno2funcId id) {
		this.id = id;
	}

	public int getMutId() {
		return this.mutId;
	}

	public void setMutId(int mutId) {
		this.mutId = mutId;
	}

	public char getWt() {
		return this.wt;
	}

	public void setWt(char wt) {
		this.wt = wt;
	}

	public String getInDbSnp() {
		return this.inDbSnp;
	}

	public void setInDbSnp(String inDbSnp) {
		this.inDbSnp = inDbSnp;
	}

	public String getInSp() {
		return this.inSp;
	}

	public void setInSp(String inSp) {
		this.inSp = inSp;
	}

	public String getInPmd() {
		return this.inPmd;
	}

	public void setInPmd(String inPmd) {
		this.inPmd = inPmd;
	}

	public String getIn1kg() {
		return this.in1kg;
	}

	public void setIn1kg(String in1kg) {
		this.in1kg = in1kg;
	}

	public String getSnapStatus() {
		return this.snapStatus;
	}

	public void setSnapStatus(String snapStatus) {
		this.snapStatus = snapStatus;
	}

	public String getSnapBin() {
		return this.snapBin;
	}

	public void setSnapBin(String snapBin) {
		this.snapBin = snapBin;
	}

	public Byte getSnapScore() {
		return this.snapScore;
	}

	public void setSnapScore(Byte snapScore) {
		this.snapScore = snapScore;
	}

	public Boolean getSnapRi() {
		return this.snapRi;
	}

	public void setSnapRi(Boolean snapRi) {
		this.snapRi = snapRi;
	}

	public Byte getSnapAcc() {
		return this.snapAcc;
	}

	public void setSnapAcc(Byte snapAcc) {
		this.snapAcc = snapAcc;
	}

	public String getSiftBin() {
		return this.siftBin;
	}

	public void setSiftBin(String siftBin) {
		this.siftBin = siftBin;
	}

	public Float getSiftScore() {
		return this.siftScore;
	}

	public void setSiftScore(Float siftScore) {
		this.siftScore = siftScore;
	}

	public Byte getPercWt() {
		return this.percWt;
	}

	public void setPercWt(Byte percWt) {
		this.percWt = percWt;
	}

	public Byte getPercMt() {
		return this.percMt;
	}

	public void setPercMt(Byte percMt) {
		this.percMt = percMt;
	}

	public Byte getPssmWt() {
		return this.pssmWt;
	}

	public void setPssmWt(Byte pssmWt) {
		this.pssmWt = pssmWt;
	}

	public Byte getPssmMt() {
		return this.pssmMt;
	}

	public void setPssmMt(Byte pssmMt) {
		this.pssmMt = pssmMt;
	}

	public Float getPsicWt() {
		return this.psicWt;
	}

	public void setPsicWt(Float psicWt) {
		this.psicWt = psicWt;
	}

	public Float getPsicMt() {
		return this.psicMt;
	}

	public void setPsicMt(Float psicMt) {
		this.psicMt = psicMt;
	}

	public String getPph2() {
		return this.pph2;
	}

	public void setPph2(String pph2) {
		this.pph2 = pph2;
	}

}
