package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * Omim2disease generated by hbm2java
 */
public class Omim2disease implements java.io.Serializable {

	private Omim2diseaseId id;
	private String phenotype;
	private String gene;
	private String mutationRaw;
	private Character wt;
	private Integer pos;
	private Character mt;

	public Omim2disease() {
	}

	public Omim2disease(Omim2diseaseId id) {
		this.id = id;
	}

	public Omim2disease(Omim2diseaseId id, String phenotype, String gene,
			String mutationRaw, Character wt, Integer pos, Character mt) {
		this.id = id;
		this.phenotype = phenotype;
		this.gene = gene;
		this.mutationRaw = mutationRaw;
		this.wt = wt;
		this.pos = pos;
		this.mt = mt;
	}

	public Omim2diseaseId getId() {
		return this.id;
	}

	public void setId(Omim2diseaseId id) {
		this.id = id;
	}

	public String getPhenotype() {
		return this.phenotype;
	}

	public void setPhenotype(String phenotype) {
		this.phenotype = phenotype;
	}

	public String getGene() {
		return this.gene;
	}

	public void setGene(String gene) {
		this.gene = gene;
	}

	public String getMutationRaw() {
		return this.mutationRaw;
	}

	public void setMutationRaw(String mutationRaw) {
		this.mutationRaw = mutationRaw;
	}

	public Character getWt() {
		return this.wt;
	}

	public void setWt(Character wt) {
		this.wt = wt;
	}

	public Integer getPos() {
		return this.pos;
	}

	public void setPos(Integer pos) {
		this.pos = pos;
	}

	public Character getMt() {
		return this.mt;
	}

	public void setMt(Character mt) {
		this.mt = mt;
	}

}
