package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SeqsPmd generated by hbm2java
 */
public class SeqsPmd implements java.io.Serializable {

	private SeqsPmdId id;
	private String md5;
	private String seq;
	private Integer taxid;

	public SeqsPmd() {
	}

	public SeqsPmd(SeqsPmdId id, String md5, String seq) {
		this.id = id;
		this.md5 = md5;
		this.seq = seq;
	}

	public SeqsPmd(SeqsPmdId id, String md5, String seq, Integer taxid) {
		this.id = id;
		this.md5 = md5;
		this.seq = seq;
		this.taxid = taxid;
	}

	public SeqsPmdId getId() {
		return this.id;
	}

	public void setId(SeqsPmdId id) {
		this.id = id;
	}

	public String getMd5() {
		return this.md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public Integer getTaxid() {
		return this.taxid;
	}

	public void setTaxid(Integer taxid) {
		this.taxid = taxid;
	}

}
