package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * Snps1kgId generated by hbm2java
 */
public class Snps1kgId implements java.io.Serializable {

	private String md5;
	private int pos;
	private char mt;

	public Snps1kgId() {
	}

	public Snps1kgId(String md5, int pos, char mt) {
		this.md5 = md5;
		this.pos = pos;
		this.mt = mt;
	}

	public String getMd5() {
		return this.md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	public int getPos() {
		return this.pos;
	}

	public void setPos(int pos) {
		this.pos = pos;
	}

	public char getMt() {
		return this.mt;
	}

	public void setMt(char mt) {
		this.mt = mt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Snps1kgId))
			return false;
		Snps1kgId castOther = (Snps1kgId) other;

		return ((this.getMd5() == castOther.getMd5()) || (this.getMd5() != null
				&& castOther.getMd5() != null && this.getMd5().equals(
				castOther.getMd5())))
				&& (this.getPos() == castOther.getPos())
				&& (this.getMt() == castOther.getMt());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMd5() == null ? 0 : this.getMd5().hashCode());
		result = 37 * result + this.getPos();
		result = 37 * result + this.getMt();
		return result;
	}

}
