package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SnpsPmdId generated by hbm2java
 */
public class SnpsPmdId implements java.io.Serializable {

	private int mutId;
	private String md5;
	private String pmdId;
	private byte nr;
	private String authors;
	private String journal;
	private String title;
	private String medline;
	private String crossref;
	private String uniprotId;
	private String ensemblId;
	private String otherRef;
	private String protein;
	private String source;
	private String expressionSys;
	private String mutPmd;
	private String mutReal;
	private String function;
	private Byte fb;
	private String structure;
	private Byte strB;
	private String stability;
	private Byte staB;
	private String expression;
	private Byte eb;
	private String transport;
	private Byte tb;
	private String maturation;
	private Byte mb;
	private String disease;
	private Byte db;
	private String uniReal;
	private String uniRealid;
	private Integer uniStart;
	private Integer uniFinish;
	private Integer uniqStart;
	private Integer uniqFinish;
	private Integer uniLoc;
	private String ensReal;
	private Integer ensOrganism;
	private Integer ensStart;
	private Integer ensFinish;
	private Integer ensqStart;
	private Integer ensqFinish;
	private Integer ensLoc;
	private short posReal;
	private char mtReal;
	private Integer taxid;

	public SnpsPmdId() {
	}

	public SnpsPmdId(int mutId, String md5, String pmdId, byte nr,
			String mutPmd, String mutReal, short posReal, char mtReal) {
		this.mutId = mutId;
		this.md5 = md5;
		this.pmdId = pmdId;
		this.nr = nr;
		this.mutPmd = mutPmd;
		this.mutReal = mutReal;
		this.posReal = posReal;
		this.mtReal = mtReal;
	}

	public SnpsPmdId(int mutId, String md5, String pmdId, byte nr,
			String authors, String journal, String title, String medline,
			String crossref, String uniprotId, String ensemblId,
			String otherRef, String protein, String source,
			String expressionSys, String mutPmd, String mutReal,
			String function, Byte fb, String structure, Byte strB,
			String stability, Byte staB, String expression, Byte eb,
			String transport, Byte tb, String maturation, Byte mb,
			String disease, Byte db, String uniReal, String uniRealid,
			Integer uniStart, Integer uniFinish, Integer uniqStart,
			Integer uniqFinish, Integer uniLoc, String ensReal,
			Integer ensOrganism, Integer ensStart, Integer ensFinish,
			Integer ensqStart, Integer ensqFinish, Integer ensLoc,
			short posReal, char mtReal, Integer taxid) {
		this.mutId = mutId;
		this.md5 = md5;
		this.pmdId = pmdId;
		this.nr = nr;
		this.authors = authors;
		this.journal = journal;
		this.title = title;
		this.medline = medline;
		this.crossref = crossref;
		this.uniprotId = uniprotId;
		this.ensemblId = ensemblId;
		this.otherRef = otherRef;
		this.protein = protein;
		this.source = source;
		this.expressionSys = expressionSys;
		this.mutPmd = mutPmd;
		this.mutReal = mutReal;
		this.function = function;
		this.fb = fb;
		this.structure = structure;
		this.strB = strB;
		this.stability = stability;
		this.staB = staB;
		this.expression = expression;
		this.eb = eb;
		this.transport = transport;
		this.tb = tb;
		this.maturation = maturation;
		this.mb = mb;
		this.disease = disease;
		this.db = db;
		this.uniReal = uniReal;
		this.uniRealid = uniRealid;
		this.uniStart = uniStart;
		this.uniFinish = uniFinish;
		this.uniqStart = uniqStart;
		this.uniqFinish = uniqFinish;
		this.uniLoc = uniLoc;
		this.ensReal = ensReal;
		this.ensOrganism = ensOrganism;
		this.ensStart = ensStart;
		this.ensFinish = ensFinish;
		this.ensqStart = ensqStart;
		this.ensqFinish = ensqFinish;
		this.ensLoc = ensLoc;
		this.posReal = posReal;
		this.mtReal = mtReal;
		this.taxid = taxid;
	}

	public int getMutId() {
		return this.mutId;
	}

	public void setMutId(int mutId) {
		this.mutId = mutId;
	}

	public String getMd5() {
		return this.md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	public String getPmdId() {
		return this.pmdId;
	}

	public void setPmdId(String pmdId) {
		this.pmdId = pmdId;
	}

	public byte getNr() {
		return this.nr;
	}

	public void setNr(byte nr) {
		this.nr = nr;
	}

	public String getAuthors() {
		return this.authors;
	}

	public void setAuthors(String authors) {
		this.authors = authors;
	}

	public String getJournal() {
		return this.journal;
	}

	public void setJournal(String journal) {
		this.journal = journal;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getMedline() {
		return this.medline;
	}

	public void setMedline(String medline) {
		this.medline = medline;
	}

	public String getCrossref() {
		return this.crossref;
	}

	public void setCrossref(String crossref) {
		this.crossref = crossref;
	}

	public String getUniprotId() {
		return this.uniprotId;
	}

	public void setUniprotId(String uniprotId) {
		this.uniprotId = uniprotId;
	}

	public String getEnsemblId() {
		return this.ensemblId;
	}

	public void setEnsemblId(String ensemblId) {
		this.ensemblId = ensemblId;
	}

	public String getOtherRef() {
		return this.otherRef;
	}

	public void setOtherRef(String otherRef) {
		this.otherRef = otherRef;
	}

	public String getProtein() {
		return this.protein;
	}

	public void setProtein(String protein) {
		this.protein = protein;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getExpressionSys() {
		return this.expressionSys;
	}

	public void setExpressionSys(String expressionSys) {
		this.expressionSys = expressionSys;
	}

	public String getMutPmd() {
		return this.mutPmd;
	}

	public void setMutPmd(String mutPmd) {
		this.mutPmd = mutPmd;
	}

	public String getMutReal() {
		return this.mutReal;
	}

	public void setMutReal(String mutReal) {
		this.mutReal = mutReal;
	}

	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	public Byte getFb() {
		return this.fb;
	}

	public void setFb(Byte fb) {
		this.fb = fb;
	}

	public String getStructure() {
		return this.structure;
	}

	public void setStructure(String structure) {
		this.structure = structure;
	}

	public Byte getStrB() {
		return this.strB;
	}

	public void setStrB(Byte strB) {
		this.strB = strB;
	}

	public String getStability() {
		return this.stability;
	}

	public void setStability(String stability) {
		this.stability = stability;
	}

	public Byte getStaB() {
		return this.staB;
	}

	public void setStaB(Byte staB) {
		this.staB = staB;
	}

	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	public Byte getEb() {
		return this.eb;
	}

	public void setEb(Byte eb) {
		this.eb = eb;
	}

	public String getTransport() {
		return this.transport;
	}

	public void setTransport(String transport) {
		this.transport = transport;
	}

	public Byte getTb() {
		return this.tb;
	}

	public void setTb(Byte tb) {
		this.tb = tb;
	}

	public String getMaturation() {
		return this.maturation;
	}

	public void setMaturation(String maturation) {
		this.maturation = maturation;
	}

	public Byte getMb() {
		return this.mb;
	}

	public void setMb(Byte mb) {
		this.mb = mb;
	}

	public String getDisease() {
		return this.disease;
	}

	public void setDisease(String disease) {
		this.disease = disease;
	}

	public Byte getDb() {
		return this.db;
	}

	public void setDb(Byte db) {
		this.db = db;
	}

	public String getUniReal() {
		return this.uniReal;
	}

	public void setUniReal(String uniReal) {
		this.uniReal = uniReal;
	}

	public String getUniRealid() {
		return this.uniRealid;
	}

	public void setUniRealid(String uniRealid) {
		this.uniRealid = uniRealid;
	}

	public Integer getUniStart() {
		return this.uniStart;
	}

	public void setUniStart(Integer uniStart) {
		this.uniStart = uniStart;
	}

	public Integer getUniFinish() {
		return this.uniFinish;
	}

	public void setUniFinish(Integer uniFinish) {
		this.uniFinish = uniFinish;
	}

	public Integer getUniqStart() {
		return this.uniqStart;
	}

	public void setUniqStart(Integer uniqStart) {
		this.uniqStart = uniqStart;
	}

	public Integer getUniqFinish() {
		return this.uniqFinish;
	}

	public void setUniqFinish(Integer uniqFinish) {
		this.uniqFinish = uniqFinish;
	}

	public Integer getUniLoc() {
		return this.uniLoc;
	}

	public void setUniLoc(Integer uniLoc) {
		this.uniLoc = uniLoc;
	}

	public String getEnsReal() {
		return this.ensReal;
	}

	public void setEnsReal(String ensReal) {
		this.ensReal = ensReal;
	}

	public Integer getEnsOrganism() {
		return this.ensOrganism;
	}

	public void setEnsOrganism(Integer ensOrganism) {
		this.ensOrganism = ensOrganism;
	}

	public Integer getEnsStart() {
		return this.ensStart;
	}

	public void setEnsStart(Integer ensStart) {
		this.ensStart = ensStart;
	}

	public Integer getEnsFinish() {
		return this.ensFinish;
	}

	public void setEnsFinish(Integer ensFinish) {
		this.ensFinish = ensFinish;
	}

	public Integer getEnsqStart() {
		return this.ensqStart;
	}

	public void setEnsqStart(Integer ensqStart) {
		this.ensqStart = ensqStart;
	}

	public Integer getEnsqFinish() {
		return this.ensqFinish;
	}

	public void setEnsqFinish(Integer ensqFinish) {
		this.ensqFinish = ensqFinish;
	}

	public Integer getEnsLoc() {
		return this.ensLoc;
	}

	public void setEnsLoc(Integer ensLoc) {
		this.ensLoc = ensLoc;
	}

	public short getPosReal() {
		return this.posReal;
	}

	public void setPosReal(short posReal) {
		this.posReal = posReal;
	}

	public char getMtReal() {
		return this.mtReal;
	}

	public void setMtReal(char mtReal) {
		this.mtReal = mtReal;
	}

	public Integer getTaxid() {
		return this.taxid;
	}

	public void setTaxid(Integer taxid) {
		this.taxid = taxid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SnpsPmdId))
			return false;
		SnpsPmdId castOther = (SnpsPmdId) other;

		return (this.getMutId() == castOther.getMutId())
				&& ((this.getMd5() == castOther.getMd5()) || (this.getMd5() != null
						&& castOther.getMd5() != null && this.getMd5().equals(
						castOther.getMd5())))
				&& ((this.getPmdId() == castOther.getPmdId()) || (this
						.getPmdId() != null && castOther.getPmdId() != null && this
						.getPmdId().equals(castOther.getPmdId())))
				&& (this.getNr() == castOther.getNr())
				&& ((this.getAuthors() == castOther.getAuthors()) || (this
						.getAuthors() != null && castOther.getAuthors() != null && this
						.getAuthors().equals(castOther.getAuthors())))
				&& ((this.getJournal() == castOther.getJournal()) || (this
						.getJournal() != null && castOther.getJournal() != null && this
						.getJournal().equals(castOther.getJournal())))
				&& ((this.getTitle() == castOther.getTitle()) || (this
						.getTitle() != null && castOther.getTitle() != null && this
						.getTitle().equals(castOther.getTitle())))
				&& ((this.getMedline() == castOther.getMedline()) || (this
						.getMedline() != null && castOther.getMedline() != null && this
						.getMedline().equals(castOther.getMedline())))
				&& ((this.getCrossref() == castOther.getCrossref()) || (this
						.getCrossref() != null
						&& castOther.getCrossref() != null && this
						.getCrossref().equals(castOther.getCrossref())))
				&& ((this.getUniprotId() == castOther.getUniprotId()) || (this
						.getUniprotId() != null
						&& castOther.getUniprotId() != null && this
						.getUniprotId().equals(castOther.getUniprotId())))
				&& ((this.getEnsemblId() == castOther.getEnsemblId()) || (this
						.getEnsemblId() != null
						&& castOther.getEnsemblId() != null && this
						.getEnsemblId().equals(castOther.getEnsemblId())))
				&& ((this.getOtherRef() == castOther.getOtherRef()) || (this
						.getOtherRef() != null
						&& castOther.getOtherRef() != null && this
						.getOtherRef().equals(castOther.getOtherRef())))
				&& ((this.getProtein() == castOther.getProtein()) || (this
						.getProtein() != null && castOther.getProtein() != null && this
						.getProtein().equals(castOther.getProtein())))
				&& ((this.getSource() == castOther.getSource()) || (this
						.getSource() != null && castOther.getSource() != null && this
						.getSource().equals(castOther.getSource())))
				&& ((this.getExpressionSys() == castOther.getExpressionSys()) || (this
						.getExpressionSys() != null
						&& castOther.getExpressionSys() != null && this
						.getExpressionSys()
						.equals(castOther.getExpressionSys())))
				&& ((this.getMutPmd() == castOther.getMutPmd()) || (this
						.getMutPmd() != null && castOther.getMutPmd() != null && this
						.getMutPmd().equals(castOther.getMutPmd())))
				&& ((this.getMutReal() == castOther.getMutReal()) || (this
						.getMutReal() != null && castOther.getMutReal() != null && this
						.getMutReal().equals(castOther.getMutReal())))
				&& ((this.getFunction() == castOther.getFunction()) || (this
						.getFunction() != null
						&& castOther.getFunction() != null && this
						.getFunction().equals(castOther.getFunction())))
				&& ((this.getFb() == castOther.getFb()) || (this.getFb() != null
						&& castOther.getFb() != null && this.getFb().equals(
						castOther.getFb())))
				&& ((this.getStructure() == castOther.getStructure()) || (this
						.getStructure() != null
						&& castOther.getStructure() != null && this
						.getStructure().equals(castOther.getStructure())))
				&& ((this.getStrB() == castOther.getStrB()) || (this.getStrB() != null
						&& castOther.getStrB() != null && this.getStrB()
						.equals(castOther.getStrB())))
				&& ((this.getStability() == castOther.getStability()) || (this
						.getStability() != null
						&& castOther.getStability() != null && this
						.getStability().equals(castOther.getStability())))
				&& ((this.getStaB() == castOther.getStaB()) || (this.getStaB() != null
						&& castOther.getStaB() != null && this.getStaB()
						.equals(castOther.getStaB())))
				&& ((this.getExpression() == castOther.getExpression()) || (this
						.getExpression() != null
						&& castOther.getExpression() != null && this
						.getExpression().equals(castOther.getExpression())))
				&& ((this.getEb() == castOther.getEb()) || (this.getEb() != null
						&& castOther.getEb() != null && this.getEb().equals(
						castOther.getEb())))
				&& ((this.getTransport() == castOther.getTransport()) || (this
						.getTransport() != null
						&& castOther.getTransport() != null && this
						.getTransport().equals(castOther.getTransport())))
				&& ((this.getTb() == castOther.getTb()) || (this.getTb() != null
						&& castOther.getTb() != null && this.getTb().equals(
						castOther.getTb())))
				&& ((this.getMaturation() == castOther.getMaturation()) || (this
						.getMaturation() != null
						&& castOther.getMaturation() != null && this
						.getMaturation().equals(castOther.getMaturation())))
				&& ((this.getMb() == castOther.getMb()) || (this.getMb() != null
						&& castOther.getMb() != null && this.getMb().equals(
						castOther.getMb())))
				&& ((this.getDisease() == castOther.getDisease()) || (this
						.getDisease() != null && castOther.getDisease() != null && this
						.getDisease().equals(castOther.getDisease())))
				&& ((this.getDb() == castOther.getDb()) || (this.getDb() != null
						&& castOther.getDb() != null && this.getDb().equals(
						castOther.getDb())))
				&& ((this.getUniReal() == castOther.getUniReal()) || (this
						.getUniReal() != null && castOther.getUniReal() != null && this
						.getUniReal().equals(castOther.getUniReal())))
				&& ((this.getUniRealid() == castOther.getUniRealid()) || (this
						.getUniRealid() != null
						&& castOther.getUniRealid() != null && this
						.getUniRealid().equals(castOther.getUniRealid())))
				&& ((this.getUniStart() == castOther.getUniStart()) || (this
						.getUniStart() != null
						&& castOther.getUniStart() != null && this
						.getUniStart().equals(castOther.getUniStart())))
				&& ((this.getUniFinish() == castOther.getUniFinish()) || (this
						.getUniFinish() != null
						&& castOther.getUniFinish() != null && this
						.getUniFinish().equals(castOther.getUniFinish())))
				&& ((this.getUniqStart() == castOther.getUniqStart()) || (this
						.getUniqStart() != null
						&& castOther.getUniqStart() != null && this
						.getUniqStart().equals(castOther.getUniqStart())))
				&& ((this.getUniqFinish() == castOther.getUniqFinish()) || (this
						.getUniqFinish() != null
						&& castOther.getUniqFinish() != null && this
						.getUniqFinish().equals(castOther.getUniqFinish())))
				&& ((this.getUniLoc() == castOther.getUniLoc()) || (this
						.getUniLoc() != null && castOther.getUniLoc() != null && this
						.getUniLoc().equals(castOther.getUniLoc())))
				&& ((this.getEnsReal() == castOther.getEnsReal()) || (this
						.getEnsReal() != null && castOther.getEnsReal() != null && this
						.getEnsReal().equals(castOther.getEnsReal())))
				&& ((this.getEnsOrganism() == castOther.getEnsOrganism()) || (this
						.getEnsOrganism() != null
						&& castOther.getEnsOrganism() != null && this
						.getEnsOrganism().equals(castOther.getEnsOrganism())))
				&& ((this.getEnsStart() == castOther.getEnsStart()) || (this
						.getEnsStart() != null
						&& castOther.getEnsStart() != null && this
						.getEnsStart().equals(castOther.getEnsStart())))
				&& ((this.getEnsFinish() == castOther.getEnsFinish()) || (this
						.getEnsFinish() != null
						&& castOther.getEnsFinish() != null && this
						.getEnsFinish().equals(castOther.getEnsFinish())))
				&& ((this.getEnsqStart() == castOther.getEnsqStart()) || (this
						.getEnsqStart() != null
						&& castOther.getEnsqStart() != null && this
						.getEnsqStart().equals(castOther.getEnsqStart())))
				&& ((this.getEnsqFinish() == castOther.getEnsqFinish()) || (this
						.getEnsqFinish() != null
						&& castOther.getEnsqFinish() != null && this
						.getEnsqFinish().equals(castOther.getEnsqFinish())))
				&& ((this.getEnsLoc() == castOther.getEnsLoc()) || (this
						.getEnsLoc() != null && castOther.getEnsLoc() != null && this
						.getEnsLoc().equals(castOther.getEnsLoc())))
				&& (this.getPosReal() == castOther.getPosReal())
				&& (this.getMtReal() == castOther.getMtReal())
				&& ((this.getTaxid() == castOther.getTaxid()) || (this
						.getTaxid() != null && castOther.getTaxid() != null && this
						.getTaxid().equals(castOther.getTaxid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMutId();
		result = 37 * result
				+ (getMd5() == null ? 0 : this.getMd5().hashCode());
		result = 37 * result
				+ (getPmdId() == null ? 0 : this.getPmdId().hashCode());
		result = 37 * result + this.getNr();
		result = 37 * result
				+ (getAuthors() == null ? 0 : this.getAuthors().hashCode());
		result = 37 * result
				+ (getJournal() == null ? 0 : this.getJournal().hashCode());
		result = 37 * result
				+ (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result
				+ (getMedline() == null ? 0 : this.getMedline().hashCode());
		result = 37 * result
				+ (getCrossref() == null ? 0 : this.getCrossref().hashCode());
		result = 37 * result
				+ (getUniprotId() == null ? 0 : this.getUniprotId().hashCode());
		result = 37 * result
				+ (getEnsemblId() == null ? 0 : this.getEnsemblId().hashCode());
		result = 37 * result
				+ (getOtherRef() == null ? 0 : this.getOtherRef().hashCode());
		result = 37 * result
				+ (getProtein() == null ? 0 : this.getProtein().hashCode());
		result = 37 * result
				+ (getSource() == null ? 0 : this.getSource().hashCode());
		result = 37
				* result
				+ (getExpressionSys() == null ? 0 : this.getExpressionSys()
						.hashCode());
		result = 37 * result
				+ (getMutPmd() == null ? 0 : this.getMutPmd().hashCode());
		result = 37 * result
				+ (getMutReal() == null ? 0 : this.getMutReal().hashCode());
		result = 37 * result
				+ (getFunction() == null ? 0 : this.getFunction().hashCode());
		result = 37 * result + (getFb() == null ? 0 : this.getFb().hashCode());
		result = 37 * result
				+ (getStructure() == null ? 0 : this.getStructure().hashCode());
		result = 37 * result
				+ (getStrB() == null ? 0 : this.getStrB().hashCode());
		result = 37 * result
				+ (getStability() == null ? 0 : this.getStability().hashCode());
		result = 37 * result
				+ (getStaB() == null ? 0 : this.getStaB().hashCode());
		result = 37
				* result
				+ (getExpression() == null ? 0 : this.getExpression()
						.hashCode());
		result = 37 * result + (getEb() == null ? 0 : this.getEb().hashCode());
		result = 37 * result
				+ (getTransport() == null ? 0 : this.getTransport().hashCode());
		result = 37 * result + (getTb() == null ? 0 : this.getTb().hashCode());
		result = 37
				* result
				+ (getMaturation() == null ? 0 : this.getMaturation()
						.hashCode());
		result = 37 * result + (getMb() == null ? 0 : this.getMb().hashCode());
		result = 37 * result
				+ (getDisease() == null ? 0 : this.getDisease().hashCode());
		result = 37 * result + (getDb() == null ? 0 : this.getDb().hashCode());
		result = 37 * result
				+ (getUniReal() == null ? 0 : this.getUniReal().hashCode());
		result = 37 * result
				+ (getUniRealid() == null ? 0 : this.getUniRealid().hashCode());
		result = 37 * result
				+ (getUniStart() == null ? 0 : this.getUniStart().hashCode());
		result = 37 * result
				+ (getUniFinish() == null ? 0 : this.getUniFinish().hashCode());
		result = 37 * result
				+ (getUniqStart() == null ? 0 : this.getUniqStart().hashCode());
		result = 37
				* result
				+ (getUniqFinish() == null ? 0 : this.getUniqFinish()
						.hashCode());
		result = 37 * result
				+ (getUniLoc() == null ? 0 : this.getUniLoc().hashCode());
		result = 37 * result
				+ (getEnsReal() == null ? 0 : this.getEnsReal().hashCode());
		result = 37
				* result
				+ (getEnsOrganism() == null ? 0 : this.getEnsOrganism()
						.hashCode());
		result = 37 * result
				+ (getEnsStart() == null ? 0 : this.getEnsStart().hashCode());
		result = 37 * result
				+ (getEnsFinish() == null ? 0 : this.getEnsFinish().hashCode());
		result = 37 * result
				+ (getEnsqStart() == null ? 0 : this.getEnsqStart().hashCode());
		result = 37
				* result
				+ (getEnsqFinish() == null ? 0 : this.getEnsqFinish()
						.hashCode());
		result = 37 * result
				+ (getEnsLoc() == null ? 0 : this.getEnsLoc().hashCode());
		result = 37 * result + this.getPosReal();
		result = 37 * result + this.getMtReal();
		result = 37 * result
				+ (getTaxid() == null ? 0 : this.getTaxid().hashCode());
		return result;
	}

}
