package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SnpsSpId generated by hbm2java
 */
public class SnpsSpId implements java.io.Serializable {

	private String md5;
	private String ac;
	private short pos;
	private char mt;
	private String kind;

	public SnpsSpId() {
	}

	public SnpsSpId(String md5, String ac, short pos, char mt, String kind) {
		this.md5 = md5;
		this.ac = ac;
		this.pos = pos;
		this.mt = mt;
		this.kind = kind;
	}

	public String getMd5() {
		return this.md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	public String getAc() {
		return this.ac;
	}

	public void setAc(String ac) {
		this.ac = ac;
	}

	public short getPos() {
		return this.pos;
	}

	public void setPos(short pos) {
		this.pos = pos;
	}

	public char getMt() {
		return this.mt;
	}

	public void setMt(char mt) {
		this.mt = mt;
	}

	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SnpsSpId))
			return false;
		SnpsSpId castOther = (SnpsSpId) other;

		return ((this.getMd5() == castOther.getMd5()) || (this.getMd5() != null
				&& castOther.getMd5() != null && this.getMd5().equals(
				castOther.getMd5())))
				&& ((this.getAc() == castOther.getAc()) || (this.getAc() != null
						&& castOther.getAc() != null && this.getAc().equals(
						castOther.getAc())))
				&& (this.getPos() == castOther.getPos())
				&& (this.getMt() == castOther.getMt())
				&& ((this.getKind() == castOther.getKind()) || (this.getKind() != null
						&& castOther.getKind() != null && this.getKind()
						.equals(castOther.getKind())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMd5() == null ? 0 : this.getMd5().hashCode());
		result = 37 * result + (getAc() == null ? 0 : this.getAc().hashCode());
		result = 37 * result + this.getPos();
		result = 37 * result + this.getMt();
		result = 37 * result
				+ (getKind() == null ? 0 : this.getKind().hashCode());
		return result;
	}

}
