package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * SnpsPmd generated by hbm2java
 */
public class SnpsPmd implements java.io.Serializable {

	private SnpsPmdId id;

	public SnpsPmd() {
	}

	public SnpsPmd(SnpsPmdId id) {
		this.id = id;
	}

	public SnpsPmdId getId() {
		return this.id;
	}

	public void setId(SnpsPmdId id) {
		this.id = id;
	}

}
