package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * Taxid2names generated by hbm2java
 */
public class Taxid2names implements java.io.Serializable {

	private int taxid;
	private String misspelling;
	private String genbankAnamorph;
	private String scientificName;
	private String synonym;
	private String blastName;
	private String unpublishedName;
	private String genbankSynonym;
	private String equivalentName;
	private String includes;
	private String acronym;
	private String inPart;
	private String anamorph;
	private String authority;
	private String genbankCommonName;
	private String genbankAcronym;
	private String commonName;
	private String misnomer;
	private String teleomorph;

	public Taxid2names() {
	}

	public Taxid2names(int taxid) {
		this.taxid = taxid;
	}

	public Taxid2names(int taxid, String misspelling, String genbankAnamorph,
			String scientificName, String synonym, String blastName,
			String unpublishedName, String genbankSynonym,
			String equivalentName, String includes, String acronym,
			String inPart, String anamorph, String authority,
			String genbankCommonName, String genbankAcronym, String commonName,
			String misnomer, String teleomorph) {
		this.taxid = taxid;
		this.misspelling = misspelling;
		this.genbankAnamorph = genbankAnamorph;
		this.scientificName = scientificName;
		this.synonym = synonym;
		this.blastName = blastName;
		this.unpublishedName = unpublishedName;
		this.genbankSynonym = genbankSynonym;
		this.equivalentName = equivalentName;
		this.includes = includes;
		this.acronym = acronym;
		this.inPart = inPart;
		this.anamorph = anamorph;
		this.authority = authority;
		this.genbankCommonName = genbankCommonName;
		this.genbankAcronym = genbankAcronym;
		this.commonName = commonName;
		this.misnomer = misnomer;
		this.teleomorph = teleomorph;
	}

	public int getTaxid() {
		return this.taxid;
	}

	public void setTaxid(int taxid) {
		this.taxid = taxid;
	}

	public String getMisspelling() {
		return this.misspelling;
	}

	public void setMisspelling(String misspelling) {
		this.misspelling = misspelling;
	}

	public String getGenbankAnamorph() {
		return this.genbankAnamorph;
	}

	public void setGenbankAnamorph(String genbankAnamorph) {
		this.genbankAnamorph = genbankAnamorph;
	}

	public String getScientificName() {
		return this.scientificName;
	}

	public void setScientificName(String scientificName) {
		this.scientificName = scientificName;
	}

	public String getSynonym() {
		return this.synonym;
	}

	public void setSynonym(String synonym) {
		this.synonym = synonym;
	}

	public String getBlastName() {
		return this.blastName;
	}

	public void setBlastName(String blastName) {
		this.blastName = blastName;
	}

	public String getUnpublishedName() {
		return this.unpublishedName;
	}

	public void setUnpublishedName(String unpublishedName) {
		this.unpublishedName = unpublishedName;
	}

	public String getGenbankSynonym() {
		return this.genbankSynonym;
	}

	public void setGenbankSynonym(String genbankSynonym) {
		this.genbankSynonym = genbankSynonym;
	}

	public String getEquivalentName() {
		return this.equivalentName;
	}

	public void setEquivalentName(String equivalentName) {
		this.equivalentName = equivalentName;
	}

	public String getIncludes() {
		return this.includes;
	}

	public void setIncludes(String includes) {
		this.includes = includes;
	}

	public String getAcronym() {
		return this.acronym;
	}

	public void setAcronym(String acronym) {
		this.acronym = acronym;
	}

	public String getInPart() {
		return this.inPart;
	}

	public void setInPart(String inPart) {
		this.inPart = inPart;
	}

	public String getAnamorph() {
		return this.anamorph;
	}

	public void setAnamorph(String anamorph) {
		this.anamorph = anamorph;
	}

	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	public String getGenbankCommonName() {
		return this.genbankCommonName;
	}

	public void setGenbankCommonName(String genbankCommonName) {
		this.genbankCommonName = genbankCommonName;
	}

	public String getGenbankAcronym() {
		return this.genbankAcronym;
	}

	public void setGenbankAcronym(String genbankAcronym) {
		this.genbankAcronym = genbankAcronym;
	}

	public String getCommonName() {
		return this.commonName;
	}

	public void setCommonName(String commonName) {
		this.commonName = commonName;
	}

	public String getMisnomer() {
		return this.misnomer;
	}

	public void setMisnomer(String misnomer) {
		this.misnomer = misnomer;
	}

	public String getTeleomorph() {
		return this.teleomorph;
	}

	public void setTeleomorph(String teleomorph) {
		this.teleomorph = teleomorph;
	}

}
