package org.rostlab.snpdbe.domain;

// default package
// Generated 21.08.2012 14:34:26 by Hibernate Tools 3.4.0.CR1

/**
 * TaxidMerged generated by hbm2java
 */
public class TaxidMerged implements java.io.Serializable {

	private int taxidOld;
	private int taxidNew;

	public TaxidMerged() {
	}

	public TaxidMerged(int taxidOld, int taxidNew) {
		this.taxidOld = taxidOld;
		this.taxidNew = taxidNew;
	}

	public int getTaxidOld() {
		return this.taxidOld;
	}

	public void setTaxidOld(int taxidOld) {
		this.taxidOld = taxidOld;
	}

	public int getTaxidNew() {
		return this.taxidNew;
	}

	public void setTaxidNew(int taxidNew) {
		this.taxidNew = taxidNew;
	}

}
